### ISSUE TITLE
Wasn't able to get working

### ISSUE THREAD

**Issue by Andrene** [vrano714/max30102-tutorial-raspberrypi#3]
I wasn't able to get this working on my PI 3 and was wondering if there is anything else that I need, also I could figure out which gpio to plug IRD and RD into.

**Comment by Andrene** [comment]
I got it to work, sort of. Running HRCalc to get HR and SPO2 outputs (-999, False, -999, False)

**Comment by vrano714** [comment]
I hope you make everything work fine.

If you cannot make the sensor work, please check the followings:

1. enable I2C interface on Pi
1. check the connection between Pi and the sensor
1. ensure the sensor is detected (`sudo i2cdetect -y 1` will do)
1. ensure the libraries are installed

If the values you get seem wrong, please check the followings:

2. touch the sensor LED window with your finger
2. keep your finger steady while sensing
2. check the values you get, before throw them to HR/SpO2 calculation (for me, the values are around 125000 or 145000)
